name: Deploy Static Site to EC2

on:
  push:
    branches:
      - main  # or your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Decode SSH key
      run: |
        echo "$EC2_SSH_KEY" | base64 -d > private_key.pem
        chmod 600 private_key.pem
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" ./ \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.TARGET_DIR }}

